version: '3'
services:
  mongodb:
    container_name: blockr_validator_mongodb
    build: mongodb
    networks:
      - blockr

  p2p:
    container_name: blockr_p2p
    build: blockr-p2p
    ports:
      - "8082:8082"
    depends_on:
      - "mongodb"
    networks:
      - blockr

  validator_main:
    container_name: blockr_validator_main
    build: blockr-validator_main
    ports:
      - "8000:8000"
    depends_on:
      - "p2p"
    networks:
     - blockr
    restart: always

  validator_backup:
    container_name: blockr_validator_backup
    build: blockr-validator_backup
    ports:
      - "8001:8000"
    depends_on: 
      - "mongodb"
      - "p2p"
    networks:
      - blockr
    restart: always

networks:
  blockr:
    driver: bridge